apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: javavulny-qa

bases:
  - ../../base

commonLabels:
  environment: qa

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: javavulny
  - path: app-env-patch.yaml
    target:
      kind: ConfigMap
      name: javavulny-config

images:
  - name: ghcr.io/hawkablock/javaspringvulny
    newTag: latest
