name: HawkScan Demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    permissions:      
      security-events: write
      packages: read
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build and run JavaSpringVulny (Docker)
        run: docker compose up --detach --quiet-pull
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v2
        continue-on-error: true
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          githubToken: ${{ github.token }}
        env:
          HAWK_ENV: GitHub Actions
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          NO_COLOR: true
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: stackhawk.sarif
          category: StackHawk
