name: PR Security Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build and Scan PR
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run with Docker Compose
        run: docker compose up --detach

      - name: Run HawkScan
        env:
          HAWK_ENV: GitHub Actions PR
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
          NO_COLOR: true
          NO_PROGRESS: true
          SARIF_ARTIFACT: true
        continue-on-error: true
        uses: stackhawk/hawkscan-action@v2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
          githubToken: ${{ github.token }}

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: stackhawk.sarif
          category: StackHawk

      - name: Show logs on failure
        if: failure()
        run: docker compose logs
